{{- if .Values.configMap.enabled }}



apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
{{- with .Values.configMap.data }}
data:
  {{ toYaml . | nindent 2 }}
{{- end -}}




{{- end }}